# -*- coding: utf-8 -*-
"""data_analysispython2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f7xVgSHf-KL_-DcqYGx1iu0ZIj7H55yl
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv("/content/gym_members_exercise_tracking_synthetic_data.csv")

df.describe()

df.head(5)

from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
df['gender']=label.fit_transform(df['Gender'])
df.head(5)

from sklearn.preprocessing import MinMaxScaler
min_max=MinMaxScaler()
df['calories_burned']=min_max.fit_transform(np.array(df['Calories_Burned']).reshape(-1,1))
df.head(5)

df.drop('Gender',axis=1,inplace=True)
df.drop('Calories_Burned',axis=1,inplace=True)
df.head(5)

df.isnull().sum()

df['Experience_Level']=df['Experience_Level'].fillna(df['Experience_Level'].mean())
df['calories_burned']=df['calories_burned'].fillna(df['calories_burned'].mean())
df['gender']=df['gender'].fillna(df['gender'].mean())
df['Age']=df['Age'].fillna(df['Age'].mean())
df['BMI']=df['BMI'].fillna(df['BMI'].mean())
df.isnull().sum()

df_new = df[['Age', 'calories_burned', 'gender', 'Experience_Level', 'BMI']]
display(df_new.head(10))

df_new['BMI'] = df_new['BMI'].round().astype(int)
df_new.head(5)

df_new.isnull().sum()

plt.scatter(df_new['Age'],df_new['BMI'])
plt.xlabel('Age')
plt.ylabel('BMI')
plt.show()

df_bar=df_new.iloc[1:10]

plt.bar(df_bar['Age'],df_bar['BMI'])
plt.xlabel('Age')
plt.ylabel('BMI')
plt.show()

plt.bar(df_bar['Experience_Level'],df_bar['calories_burned'])
plt.xlabel('exp')
plt.ylabel('cal')
plt.show()

