# -*- coding: utf-8 -*-
"""python2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10E1sxbN1HUlodNKsQtbExEP9tf7_3siw
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
name=["manish","riya","karan","sneha","rahul"]
age=[20,21,30,25,23]
workout_hrs=[3,4,2,1,5]
calories_burnout=[300,400,200,100,500]

#printing the data
for i in range(len(name)):
  print(name[i])
  print(age[i])
  print(workout_hrs[i])
  print(calories_burnout[i])
  print("_______")

avg=sum(workout_hrs)/len(workout_hrs)
print("average:",avg)

max_cal=max(calories_burnout)
print("max calories:",max_cal)

min_cal=min(calories_burnout)
print("min calories:",min_cal)

most_cal=max(calories_burnout)
for i in range(len(name)):
  if calories_burnout[i]==most_cal:
    print("most_active member:",name[i])

min_cal=min(calories_burnout)
for i in range(len(name)):
  if calories_burnout[i]==min_cal:
    print("least active member:",name[i])

plt.plot(name,calories_burnout)
plt.xlabel("names")
plt.ylabel("calories burned")
plt.title("calories burned vs names")
plt.legend()
plt.show()

std=np.std(calories_burnout)
print("standard deviation:",std)

var=np.var(calories_burnout)
print("varience:",var)

plt.pie(x=calories_burnout, labels=name, autopct='%1.1f%%')
plt.title("pie chart")

plt.bar(workout_hrs,calories_burnout)
plt.xlabel("workout hours")
plt.ylabel("calories burned")
plt.title("calories burned vs workout hours")
plt.legend()
plt.show()

plt.pie(calories_burnout, labels=name, autopct='%1.1f%%')
plt.gca().add_artist(plt.Circle((0, 0), 0.5, color='white'))
plt.title("doughnut chart")