# -*- coding: utf-8 -*-
"""Untitled56.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ng7j89gUiLzOB-jdClyskn-Cw_k1w8cK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

marks=[50,20,30,60,80]
std_hrs=[3,1,4,5,6]

print("mean of marks:",np.mean(marks))
print("median of marks:",np.median(marks))
print("var of marks:",np.var(marks))
print("std_dv marks:",np.std(marks))
print("correl marks",np.corrcoef(marks,std_hrs))

plt.scatter(std_hrs,marks)
plt.xlabel("hrs")
plt.ylabel("marks")
plt.title("hrs vs marks")
plt.show()

plt.plot(std_hrs,marks)
plt.xlabel("hrs")
plt.ylabel("marks")
plt.title("hrs vs marks")
plt.show()

plt.pie(marks,labels=marks,autopct="%1.1f%%")
plt.show()